name: JMeter Actions
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Welcome Message
        run: |
         echo "welcome to jmeter"
      - name: Execute JMeter Test
        run: |
         chmod +x ./.github/workflows/jmeter_script.sh
         ./.github/workflows/jmeter_script.sh
