name: Jmeter Actions
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: "./Palate_App.jmx"
          args: "-l result.jtl -Jjmeter.save.saveservice.output_format=csv -Jjmeter.save.saveservice.response_data=true"
      - name: Convert JTL to CSV
        run: |
          jmeter -g result.jtl -o result
          mv result/response.csv result.csv
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.csv
      - name: Check Result Errors
        run: |
          summary=$(echo "${{ steps.jmeter.outputs.output }}" | grep -o "summary +.*")
          error_count=$(echo "$summary" | grep -o "Err: [1-9]*")
          if [ -n "$error_count" ]; then
            echo "There were errors in the JMeter result"
            exit 1
          else
            echo "No errors found in the JMeter result"
          fi
