name: Jmeter Actions
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PerfAction for JMeter
        id: jmeter
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: "./Palate_App.jmx"
      - name: Convert JTL to CSV
        run: |
          sed -e 's/<[^>]*>//g' result.jtl > result.csv
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.csv
      - name: Check Result Errors
        run: |
          error_count=$(grep -c "Err:" result.jtl | grep -v "Shutdown/StopTestNow/HeapDump/ThreadDump" || true)
          if [ "$error_count" -gt 0 ]; then
            echo "There were errors in the JMeter result"
            exit 1
          else
            echo "No errors found in the JMeter result"
          fi
          
          
